### ISSUE TITLE
Time inaccurate

### ISSUE THREAD

**Issue by Mithil467** [siesgstarena/arena-issue-tracking#1]
On 14-11-2018, at around 1:20 am I posted a blog http://siesgstarena.herokuapp.com/blog/5beb2b2221308300218e40f1. But the time shown is wrong, it shows 13-11-2018 at 7:50 am.
It is not that big of a bug, but thought its better to inform! (Plus this is the 1st time am reporting an issue like this!)

**Comment by Mithil467** [comment]
Wait now it's fixed! But the problem is with time of my comment now! It was at around 1:24 on the same day but it shows 10:36 PM now

**Comment by prabhuomkar** [comment]
Hey @Mithil467 , we have fixed your issue.
We would like to receive your acknowledgement regarding the same.

**Comment by Mithil467** [comment]
Yes! It is fixed! 👍
