### ISSUE TITLE
Wrong Graph 

### ISSUE THREAD

**Issue by vipul-08** [siesgstarena/arena-issue-tracking#10]
After the rating updated for SRM 05, there is some issue in the rating graph of the users. 
As we know the SRM 01 happened before SEPT Queue but the graph is showing wrong.
![capture](https://user-images.githubusercontent.com/25116323/50778381-d1d79500-12c3-11e9-8caa-0c4a40c40eb3.PNG)

**Comment by prabhuomkar** [comment]
Hey @vipul-08 we have fixed the issue can you check and let us know?

**Comment by vipul-08** [comment]
Yes, the issue is fixed now. It is displaying right order in the graph now.
