### ISSUE TITLE
Improvements for blog posts

### ISSUE THREAD

**Issue by prabhuomkar** [siesgstarena/arena-issue-tracking#11]
- [x] Any click on the links in the post, should open in a new tab
- [ ] Better editor with functions for writing blog posts like GitHub
- [x] Realtime Preview like GitHub for the posts
- [ ] Better code viewer for showing code snippets in blog post

**Comment by Mithil467** [comment]
And also, save as a draft option please :(

**Comment by Swap76** [comment]
Hey omkar and mithil we are working on shifting our site onto reactJS. In that we will be adding a good editor for writing posts and also the save as draft feature.
