### ISSUE TITLE
JAVA traditional compiler error 

### ISSUE THREAD

**Issue by SansBailmare** [siesgstarena/arena-issue-tracking#12]
Some packages of Java 8 are not supported by the compiler.
Either integrating the 8/10 packages will suffice or adding an option for java 8/10 compiling will solve the problem.

**Comment by Swap76** [comment]
Hey you can check now we have changed our compiler it has all features of jdk 8

**Comment by SansBailmare** [comment]
Hey Swapnil,
Good that you have solved the issue, the compiler would now allow all the
java Programmers to use the packaged functions.
Cheers to the arena Team
