### ISSUE TITLE
Formatting Total Time in Status Tab

### ISSUE THREAD

**Issue by prabhuomkar** [siesgstarena/arena-issue-tracking#13]
In the total time section of Status tab, the formatting is incorrect.  
It needs to leading 0s in the time taken.  
**Example: 2:4:30 should be 02:04:30**

**Comment by Swap76** [comment]
Hey Omkar you can now check the Scoreboard. We have fixed the issue.

**Comment by prabhuomkar** [comment]
Closing since this is solved.
