### ISSUE TITLE
 Show List of Submissions on Profile Page

### ISSUE THREAD

**Issue by prabhuomkar** [siesgstarena/arena-issue-tracking#15]
How about 2 tabs in Profile? 
- **Posts**: List of blog posts written by that user (with Pagination)
- **Submissions**: List of submissions made by that user (with Pagination)

**Comment by Swap76** [comment]
@prabhuomkar this is a good idea. We will surely work on that.

Thanks for suggestion :-)

**Comment by prabhuomkar** [comment]
Any update on this @Swap76 @Mithil467 @barath121

**Comment by Swap76** [comment]
@barath121 is taking this as his first task with mongodb

**Comment by prabhuomkar** [comment]
This is done. Closing it. Thanks guys!
