### ISSUE TITLE
Feature Request: Update Ratings Graph on User Profile

### ISSUE THREAD

**Issue by prabhuomkar** [siesgstarena/arena-issue-tracking#16]
- Have clear colour divisions for ratings 
- Have some sort of indicator when the user was able to jump divisions?
- Have ratings wise color change depicted in the graph

What do you think @Swap76 @Mithil467 @barath121

**Comment by Swap76** [comment]
Yes, it's a good idea :-)

@barath121 Start working on this issue 

**References**
https://developers.google.com/chart/interactive/docs/reference

**Examples**
http://codeforces.com/profile/rsd511

**Comment by prabhuomkar** [comment]
Closing as was done as a part of release **26.03.2020**
