### ISSUE TITLE
Bug: Disappearing Options on Status Page

### ISSUE THREAD

**Issue by prabhuomkar** [siesgstarena/arena-issue-tracking#17]
When a user selects all Problem option from Status Page to filter submissions, the results page hides all the options.
This doesn't happen when the user selects Status or Language Option.

Disappearing URL: http://arena.siesgst.ac.in/contest/SRM14/status?problem=5e2d10a1533c8d0022c770f2&language=C%2B%2B&type=Accepted

**Comment by Swap76** [comment]
@barath121 have a look at the problem it is appearing now because of new condition added for showing the options :-)

**Comment by barath121** [comment]
I found the issue :).
I will submit a solution soon.

**Comment by Swap76** [comment]
Hey @prabhuomkar the issue is solved you can check it now :-)

**Comment by prabhuomkar** [comment]
Hey @Swap76 @barath121 the issue is fixed. Closing this :) Thanks!
