### ISSUE TITLE
Unable to submit a solution after One Successful Submission

### ISSUE THREAD

**Issue by vipul-08** [siesgstarena/arena-issue-tracking#18]
I think this feature will be really helpful. After the contest ends, one can have many more approaches in mind to solve a particular problem. But no tries left.

**Comment by Swap76** [comment]
@vipul-08 Thanks for the idea we will work on an update that will allow the user to have 10 more trials after the contest ends if he/she has got Accepted as a verdict. If he/she has not got Accepted until now then they get unlimited trials to work on the solution.

**Comment by prabhuomkar** [comment]
I agree with @vipul-08 !

**Comment by Swap76** [comment]
@vipul-08 You can now check we have allowed the user to submit 10 Accepted solutions for a problem

**Comment by vipul-08** [comment]
Thanks @Swap76 and team. This feature will be really helpful for everyone. Closing it!
