### ISSUE TITLE
Feature Request for some utility api

### ISSUE THREAD

**Issue by vipul-08** [siesgstarena/arena-issue-tracking#19]
Can we have the APIs for the features under 
arena.siesgst.ac.in/apps

These features will look good in the android app.

**Comment by Swap76** [comment]
@vipul-08 Thanks for creating the issue. 

Yes, apps will be a good feature for the Android app. We will start the process of building the API. Will notify you here only when the apps API will be live or you can also check the newly added changelog section on the website

http://arena.siesgst.ac.in/api/docs

**Comment by Swap76** [comment]
@vipul-08 The App API for comparison is live, we are working on the statistics part of the apps

**Comment by Swap76** [comment]
@vipul-08 The API for Statistics are also live now you can check the latest improvements here http://arena.siesgst.ac.in/api/docs#changelog

**Comment by vipul-08** [comment]
Hi @Swap76 , already checked the statistics api, looks good to me.  Well done Team!! Closing the issue now.
