### ISSUE TITLE
Blog Feature Api Request  

### ISSUE THREAD

**Issue by kuchekarsonal** [siesgstarena/arena-issue-tracking#20]
we can also have API be created for  Blogs  section
 under
 arena.siesgst.ac.in/blog, 
that will be useful to stay updated

**Comment by Swap76** [comment]
@kuchekarsonal It's a good idea thanks for the suggestion. we will discuss this in the team and let you know here only when the work is done. 

As we are adding features to API every week slowly. Please keep an eye on the below link for updates.
http://arena.siesgst.ac.in/api/docs#changelog

**Comment by Swap76** [comment]
@kuchekarsonal We have added the API requested by you please check at the http://arena.siesgst.ac.in/api/docs#changelog

We have only given the important info related to blogs but for the content, you have to redirect them to our website using the ID provided in the blog. Expect that we have given everything from tags, owner to upvotes, downvotes, etc.

**Comment by kuchekarsonal** [comment]
Thanks for the update!
