### ISSUE TITLE
Query Users by emailID

### ISSUE THREAD

**Issue by naidukarthi2193** [siesgstarena/arena-issue-tracking#21]
GSigin can automatically send query for user details .

**Comment by Swap76** [comment]
@naidukarthi2193 That's a great idea, will add the query for fetching the user using email

We will let you know when we add the requested features in the issue or you can check for updates at   http://arena.siesgst.ac.in/api/docs#changelog

**Comment by Swap76** [comment]
@naidukarthi2193 Please check out the http://arena.siesgst.ac.in/api/docs#changelog page we have added the requested feature :-)

**Comment by naidukarthi2193** [comment]
Thanks a Lot
