### ISSUE TITLE
Along with User API data can send History of Ratings to add visualizations

### ISSUE THREAD

**Issue by naidukarthi2193** [siesgstarena/arena-issue-tracking#22]

**Comment by Swap76** [comment]
@naidukarthi2193 Can you elaborate on the history of ratings. As the latest rating change only is required or the full history from start?

**Comment by naidukarthi2193** [comment]
@Swap76 history from the start just as the same in arena website a graph of ratings

**Comment by Swap76** [comment]
@naidukarthi2193 Thanks for the info we are working on the update :-)

**Comment by Swap76** [comment]
@naidukarthi2193 We have updated the API please have a look http://arena.siesgst.ac.in/api/docs#changelog

**Comment by naidukarthi2193** [comment]
Yup Thanks a lot
