### ISSUE TITLE
API for list of submissions and querying it by username 

### ISSUE THREAD

**Issue by naidukarthi2193** [siesgstarena/arena-issue-tracking#23]

**Comment by Swap76** [comment]
@naidukarthi2193 Will first work on giving you aggregated result from submission data to build pie chart then will push the update for fetching all the submissions by username

**Comment by Swap76** [comment]
@naidukarthi2193 We have pushed the code for submission statistics in all user methods please have a look :-)

**Comment by naidukarthi2193** [comment]
Thanks a lot
