### ISSUE TITLE
In accurate pie chart data 

### ISSUE THREAD

**Issue by VarunS9000** [siesgstarena/arena-issue-tracking#26]
Pie chart data of all users have changed by a certain pattern . The pattern is 
New Wrong answer  value = New Accepted value + Old Wrong answer value 
New Compilation error = New Wrong Answer + Old Compilation error 
And so on.

**Comment by Swap76** [comment]
@SuperSayianGod9000 This is a very good analysis. Thanks for the work. We are working on fixing the issue. Will get back to you as soon as we fix the issue.

**Comment by Swap76** [comment]
@SuperSayianGod9000 Please check the API now we have fixed the issue. The analysis done by you was very helpful in solving the issue :-)

**Comment by VarunS9000** [comment]
I checked and now the API is perfect. Thanks for the swift action great job!!

**Comment by Swap76** [comment]
@SuperSayianGod9000 Please close the issue if you are satisfied with the fix
