### ISSUE TITLE
Comparator Page is Throwing Error

### ISSUE THREAD

**Issue by prabhuomkar** [siesgstarena/arena-issue-tracking#27]
When I visit: http://arena.siesgst.ac.in/apps/compare, Page is throwing error: `Cannot read property 'user' of undefined`

**Comment by Swap76** [comment]
I will solve this Issue ASAP

**Comment by Mithil467** [comment]
Can confirm this bug exists. But weirdly it doesnt reproduce on local server. I am trying to find the bug, but maybe reading the console error on heroku will help?

**Comment by Swap76** [comment]
The bug is in the initial page where results are not given I think as `http://arena.siesgst.ac.in/apps/compare?first=Swapnil76&second=AdityaP` pages like this work perfect

**Comment by prabhuomkar** [comment]
Seems its solved

**Comment by Mithil467** [comment]
Yeah it is working now, all of a sudden. After we merged my new branch. But that branch did nothing to change this behaviour. Weird.
