### ISSUE TITLE
For Statistics API need User object in Response

### ISSUE THREAD

**Issue by prabhuomkar** [siesgstarena/arena-issue-tracking#28]
API: http://arena.siesgst.ac.in/api/apps/statistics
This returns `name`, `language`, `acceptedCount` in [Statistics object](http://arena.siesgst.ac.in/api/docs#object-statistics)

Can we have [User object](http://arena.siesgst.ac.in/api/docs#object-user) instead of `name` so that we can checkout that user?

**Comment by Swap76** [comment]
We were actually thinking to now hide the API section & give access of API's to the official App of arena only.
What are your thoughts ?

**Comment by prabhuomkar** [comment]
Closing this as APIs are being deprecated
