### ISSUE TITLE
Inconsistent Behaviour

### ISSUE THREAD

**Issue by vipul-08** [siesgstarena/arena-issue-tracking#29]
Under the "WHO" column, username is shown in most of the cases, except the Scoreboard, where name is shown.
It will be great if name is shown at every place.

References:
http://arena.siesgst.ac.in/contest/SRM21/status (username is there under WHO column)
http://arena.siesgst.ac.in/contest/SRM21/scoreboard (name is there under WHO column)
http://arena.siesgst.ac.in/contest/SRM21/change (username is again there under WHO column)
http://arena.siesgst.ac.in/contest/SRM21/my (username is again there under WHO column)

**Comment by Swap76** [comment]
@vipul-08 Thanks for the suggestion will look into it and will let you know

**Comment by Swap76** [comment]
@vipul-08 Checkout the scoreboard page
Sorry for the delay

**Comment by vipul-08** [comment]
LGTM! You can close this now
