### ISSUE TITLE
Problem solved or not?

### ISSUE THREAD

**Issue by Mithil467** [siesgstarena/arena-issue-tracking#3]
Can we have an indicator in problem set for solved/unsolved problems?

**Comment by prabhuomkar** [comment]
Yeah, its a WIP. We will be finishing it very soon 👍

**Comment by Swap76** [comment]
Hey @Mithil467 , we have added the enhancement as requested.
We would like to receive your acknowledgement regarding the same.

**Comment by Mithil467** [comment]
I had submitted solutions for AUG18A, AUG18C for sure. But they have disappeared somehow :(. Other than that yes it is working fine, in fact I just attempted an unattempted question to see if it shows solved or not solved or wrong, and it did work. Good job! Thanks
