### ISSUE TITLE
The clickable button doesn't makes sense

### ISSUE THREAD

**Issue by vipul-08** [siesgstarena/arena-issue-tracking#30]
![imageonline-co-writeimage](https://user-images.githubusercontent.com/25116323/113357663-f8c98800-9361-11eb-9d62-9a8874b8a213.jpg)

The button shown above is clickable and clicking it results in below scenario which should be ignored:

![image](https://user-images.githubusercontent.com/25116323/113357762-231b4580-9362-11eb-9352-fd5360774dfb.png)

**Comment by Swap76** [comment]
@vipul-08 Thanks for the issue will solve it and let you know

**Comment by Swap76** [comment]
@vipul-08 Please check the website now, we have solved the issue.
Thanks for letting us know the Problem.

**Comment by vipul-08** [comment]
The cursor is still pointer, other than that, LGTM 👍
