### ISSUE TITLE
All problems are not visible with the help of tags

### ISSUE THREAD

**Issue by shambhavisudarsan** [siesgstarena/arena-issue-tracking#5]
Individual tags do not search a problem with one such tag. We have to search all the tags for finding a particular problem.

**Comment by Mithil467** [comment]
But I didn't face this issue. Can you please explain the case further?

**Comment by prabhuomkar** [comment]
Hey @ShambhaviSudarsan 

We have tracked and logged this issue of not getting all the problems of a specific tag e.g. _math_
(we are missing problems which are both adhoc and math i.e. which includes math as tag with other tags for a problem).

This issue will be fixed as we are facing problems with our internal tag management system.

**Comment by Mithil467** [comment]
But I am getting the correct results, like searching math gives adhoc, math as well!
![screenshot from 2018-12-18 21-22-38](https://user-images.githubusercontent.com/41439841/50165538-23b37d80-030b-11e9-972d-77c1085da813.png)

**Comment by prabhuomkar** [comment]
@Mithil467 Its the Problem Set Page where you can click on any tag to list problems by that tag. 
We'll be fixing it soon.

**Comment by prabhuomkar** [comment]
Hey @ShambhaviSudarsan !
We have fixed the mentioned issue in problem set page.

Let us know, if the issue persists.

**Comment by Mithil467** [comment]
This problem is solved but I noticed another small problem. Please look at this question SRM01B in the table. The tag is not separated it is a single tag unlike others. ("adhoc, strings"). The problem with this is that we can't click single tag and when you click on let's say strings in some other question, this question isn't displayed.

**Comment by Mithil467** [comment]
Yeah somehow it is solved now!
