### ISSUE TITLE
Create a new blog option maybe isn't intentional?

### ISSUE THREAD

**Issue by Mithil467** [siesgstarena/arena-issue-tracking#6]
Let's say you go to this user profile for Omkar Prabhu http://arena.siesgst.ac.in/profile/5b5c89298114180020d4bcb0 here you see he has quite a few blogs written. Now let's see this user profile http://arena.siesgst.ac.in/profile/5b6c6860746b5e0020a32aa7 which has 0  blogs. Now it should not be showing us the option to 'Write a blog post now ' right?

**Comment by prabhuomkar** [comment]
Hey Mithil, 

This was not intentional, this was a bug.
We have fixed this for all the users in the latest patch release.
Let us know, if the issue persists.

Thanks 👍

**Comment by Mithil467** [comment]
Glad to help!
