### ISSUE TITLE
Links on the feature set blog post

### ISSUE THREAD

**Issue by Mithil467** [siesgstarena/arena-issue-tracking#8]
http://arena.siesgst.ac.in/blog/5b994c66d8a6990020791b04 This is our feature set blog post. But the links aren't working on the page. Like Apps for instance. The link takes you to http://arena.siesgst.ac.in/blog/%22http://siesgstarena.herokuapp.com/apps%22 as opposd to simply http://siesgstarena.herokuapp.com/apps. %22 is adding a " in the link (as per html url encoding ascii reference).

**Comment by prabhuomkar** [comment]
**Issue Tracking is to deal with platform bugs, feature requests, etc.**
This is a "user error" in writing blog posts, as we converted old HTML posts to support markdown.

PS: The links on the post were fixed almost 18 hours ago.

**Comment by Mithil467** [comment]
Oh! Alright, glad to know it's just a small user error then, as I thought html is still functional. :+1:
